#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define AUTO_SHIFT_TIMEOUT 145
#define SERIAL_NUMBER "7yO6p/PBB3wL"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60



// custom QMK settings
#define RETRO_SHIFT 500